config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # ルートページ
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"

  resources :books, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  # get 'books/index'
  # get 'books/show'

  resources :users, only:[:show, :edit, :update, :index]
  # get 'users/edit'
  # get 'users/index'
  # get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum:2, maximum:20}
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resouce)
    # サインインした後に遷移する場所（一旦aboutページ。実際はuserページ＊後で変更）
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resouce)
    # サインアウトしたらルートページに遷移する
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to  book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @book_show = Book.find(params[:id])
    @user = User.find(@book_show.user_id)
  end

  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end

  def update
    is_matching_login_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user_id = book.user_id.to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to "/books"
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = @user.books
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(login_user_id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
      <div class="md-3">
        <h2 class="mt-3">New book</h2>
        <div class="form-group">
        <%= form_with model: book, url: '/books', method: :post do |f| %>
          <label for="book_title">Title</label>
          <%= f.text_field :title, id:"book_title", class:"form-control" %><br />
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, id:"book_body", class:"form-control" %><br />
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
        </div>
      </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-8 col-sm-8 col-lg-7 col-xl-5">

      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %>error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="Title">Title</label>
          <%= f.text_field :title, id:"Title", placeholder:"Book title", class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="Body">Opinion</label>
          <%= f.text_area :body, id:"Body", placeholder:"Book opinion", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class:"btn btn-success" %>
        </div>
      <% end %>
      <div>
        <%= link_to "Show", book_path(@book.id) %> |
        <%= link_to "Back", "/books" %>
      </div>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">

    <% if @book != nil && @book.errors.any? %>
      <h3>
        <%= @book.errors.count %>error prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tr>
          <%= image_tag @user.get_profile_image(100,100) %>
        </tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>

      <div class="row">
        <%= link_to '<i class="fas fa-user-cog"></i>'.html_safe, edit_user_path(@user), class:"btn btn-outline-secondary btn-block" %>
      </div>

      <%= render 'new', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to image_tag(book.user.get_profile_image(80,80)), user_path(book.user)  %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/info', user: @user %>

      <div class="row">
        <%= link_to '<i class="fas fa-user-cog"></i>'.html_safe, edit_user_path(@user), class:"btn btn-outline-secondary btn-block" %>
      </div>

      <%= render 'new', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <td>
            <%= image_tag @book_show.user.get_profile_image(100,100) %><br />
            <%= link_to @book_show.user.name, user_path(@book_show.user.id)%>
          </td>
          <td>
            <%= link_to @book_show.title, book_path(@book_show) %>
          </td>
          <td>
            <%= @book_show.body%>
          </td>
          <% if @book_show.user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path(@book_show), class:"btn btn-success  btn-sm" %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book_show), method: :delete, class:"btn btn-danger  btn-sm", "data-confirm" => "本当に削除しますか？"  %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="text-center">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
    <p>you can share exchange your opinions, inpressions , and emotions</p>
    <p>about various books!</p>

      <div class="row">
        <div class="mx-auto col-10">
          <a  href="/users/sign_in" type="button" class="btn btn-info btn-sm btn-block">Log in</a>
          <a  href="/users/sign_up" type="button" class="btn btn-success btn-sm btn-block">Sign up</a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container">
        <a class="navbar-brand" href="/">Bookers</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto fa-ul">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-home'></i> Home".html_safe, user_path(current_user.id), class: "nav-link text-light" %>
            </li>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-users'></i> Users".html_safe, "/users", class: "nav-link text-light" %>
            </li>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-book-open'></i> Books".html_safe, "/books", class: "nav-link text-light" %>
            </li>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-sign-out-alt'></i> Log out".html_safe, destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-home'></i> Home".html_safe, root_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-link'></i> About".html_safe, about_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-user-plus'></i> Sign up".html_safe, new_user_registration_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item active">
              <%= link_to "<i class='fas fa-sign-in-alt'></i> Log in".html_safe, new_user_session_path, class: "nav-link text-light" %>
            </li>
          <% end %>
          </ul>
        </div>

        </div>

      </nav>
    </header>

    <main>
      <p id="notion"><%= flash[:notice] %></p>
    <%= yield %>
    </main>

    <footer class="footer">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
      <table class="table">
        <tr>
          <%= image_tag user.get_profile_image(100,100) %>
        </tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h2>User info</h2>

      <% if @user.errors.any? %>
        <h3>
          <%= @user.errors.count %>error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do|f| %>
        <div class="form-group">
          <label for="Name">Name</label>
          <%= f.text_field :name, autofocus:true, id:"Name", placeholder:"名前", class:"form-control" %><br />
        </div>
        <div class="form-group">
          <label for="Image">Image</label>
          <%= f.file_field :profile_image, placeholder:"プロフィール画像", accept: "image/*", class:"form-control-file user_image"  %><br />
        </div>
        <div class="form-group">
          <label for="Introduction">Introduction</label>
          <%= f.text_area :introduction, rows:"3", id:"Introduction", placeholder:"自己紹介", class:"form-control" %><br />
        </div>
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'info', user: @user %>

      <div class="row">
        <%= link_to '<i class="fas fa-user-cog"></i>'.html_safe, edit_user_path(@user), class:"btn btn-outline-secondary btn-block" %>
      </div>

      <%= render 'books/new', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(80,80) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<!--ユーザーの詳細画面-->

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'info', user: @user %>

      <div class="row">
        <%= link_to '<i class="fas fa-user-cog"></i>'.html_safe, edit_user_path(@user), class:"btn btn-outline-secondary btn-block" %>
      </div>

      <%= render 'books/new', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to image_tag(book.user.get_profile_image(80,80)) %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>